### PR TITLE
[WIP] L.Rectangle and L.Circle editing support

### LINKED ISSUE #39: Support drawing/editing of L.Rectangle

### PR DESCRIPTION
**Pull request by yohanboniface**
Work in progress!

Fix #39

### CODE REVIEW

**Comment by sdeoGit** [comment]
When will the feature of rectangle edit be moved to main release? How stable is the dev version, which has this feature, to start using into my application development?

**Comment by yohanboniface** [comment]
I think the Leaflet.Editable 0.7.0-beta version is even more stable and tested than the 0.6.2. But it's not released yet because it needs a non released Leaflet version. Which, at its turn, is quite stable too, and imho can be used in production (we are about to publish a rc1).

**Comment by sdeoGit** [comment]
I just pulled Leaflet.Editable 0.7.0-beta , but could not find rectangle edit support in that version.
am I missing something ?

**Comment by yohanboniface** [comment]
Yes, it's not in the npm release, just in the master. I'll release a new one when we release the Leaflet rc1.

**Comment by sdeoGit** [comment]
Thanks  :)

**Pull request merged**
