### PR TITLE
onDrawingClick: ignore if right button click

### LINKED ISSUE #156: right click draws a new vertex
Currently there is no way to set a specific button for drawing. As a result the leaflet context menu event is not triggered on the mouse right click and instead a new vertex gets drawn

### PR DESCRIPTION
**Pull request by AndrejsCistoserdovs**
Ignores mouse right button clicks. Added option to be able to swap button behaviour
Fixes #156

### CODE REVIEW

**Comment by yohanboniface** [comment]
Hi, thanks for the contribution!
I'm a bit surprised we need this: the `onDrawingClick` is supposed to be on `click` which is left button per Leaflet code. Feel like there is something else around.
Can you set up a JSFiddle to demonstrate the issue so it's easier to investigate?

**Comment by tenznhok** [comment]
How to swap the mouse click button to right mouse click to start the draw?

**Comment by luiscamachopt** [comment]
> the onDrawingClick is supposed to be on click which is left button per Leaflet code
onDrawingClick is called from the onMouseup so it's called for any mouse click

**Comment by yohanboniface** [comment]
> onDrawingClick is called from the onMouseup so it's called for any mouse click

Ah, good point, makes sense!
So I think the right fix is not to run `L.Editable.onMouseDown` if the button is not the left one.
Anyone up for a PR with this quick fix (with a test, and making sure it does not break the touch) ?

**Pull request closed without merging**
