### PR TITLE
fix polyline line guide not attached after continue forward

### PR DESCRIPTION
**Pull request by sidloki**
Calling `continueForward()` does not show the dashed line guide for polylines. `continueBackward()` works fine therefore I created a similar `startDrawingForward` function to attach the line guide.

### CODE REVIEW

**Comment by yohanboniface** [comment]
I confirm the bug, but how that change would fix it?

I think the issue is related to https://github.com/Leaflet/Leaflet.Editable/commit/b59bc4c940c0e14fbf9dac9d142a92b275ed1d1a or https://github.com/Leaflet/Leaflet.Editable/commit/173cb8cb890b9b5e9baf52561a0eb57aba2cd25e

**Comment by sidloki** [comment]
The example `continue-line.html` works as expected with the fix.

The `continueForward` function calls now the `L.Editable.PolylineEditor.startDrawingForward` instead of `L.Editable.PathEditor.startDrawingForward`.

**Comment by sidloki** [comment]
An other way to fix it, is to call the parent function and then attach the line guide:
```
startDrawingForward: function () {
    L.Editable.PathEditor.prototype.startDrawingForward.call(this);
    this.tools.attachForwardLineGuide();
}
```

**Comment by yohanboniface** [comment]
It would be nice to understand how this has been broken before deciding for the right fix ;)
Also, if you feel the energy, a unit test to be sure it does not break again would be awesome :)

**Comment by sidloki** [comment]
I think the commit b59bc4c, which you mentioned, is the reason.
Unit tests will (hopefully) follow...

**Comment by yohanboniface** [comment]
I don't think `startDrawingForward` should always attach the drawing guides, because it will fail in canvas mode when the geometry is invalid. This needs a bit more thinking IMHO.
Basically, we want to add it when drawing and at least one point exists on the geometry.

**Comment by yohanboniface** [comment]
Maybe those lines should be moved back to the `startDrawingXXX` methods, but keeping the test on the latlngs (minus one if moved back): https://github.com/Leaflet/Leaflet.Editable/commit/173cb8cb890b9b5e9baf52561a0eb57aba2cd25e#diff-18d1ca5166302e5961795e072cfb1b4bR1122

**Comment by sidloki** [comment]
I think it's best to attach the line guides directly in the continueX instead of startDrawingX methods and to check before that, whether at least one point was drawn.

I've updated the PR and also created some unit tests which fails without the fix.

**Comment by yohanboniface** [comment]
Thanks! :)

**Pull request merged**
