### PR TITLE
Better Rectangle and Circle drawing

### PR DESCRIPTION
**Pull request by xoqem**
Rectangles and circles only dispatch commit when the shape is finalized.  Rectangles can draw in any direction now, not just from the top left.

### CODE REVIEW

**Comment by xoqem** [comment]
There was some good feedback in one of the related issues regarding problems after the rectangle is initially drawn that I need to fix in this PR.  Will play with some ideas as I have time and update if I come up with a decent solution.

**Comment by xoqem** [comment]
Ok, I looked into the problem report on issue #87, and the behavior in this PR actually seems ok.  When drawing, we know what vertex should be anchored, but not so much when editing an already drawn shape.  The behavior in this PR when editing an existing rectangle appears to match the existing behavior, so it seems acceptable.

**Comment by xoqem** [comment]
Decided to fix the behavior that I added that allowed for drawing rectangles or circles with two clicks instead of just dragging.  The reason the behavior was there was because mouse up wasn't always firing after mouse down (only mouse click if the mouse didn't move much, which seemed incorrect).  However, this is breaking a marker test.  I'll look into either fixing the test, or changing mouse up to only fire if click doesn't and add click handler in addition to mouse up to rectangle and circle editors.

**Comment by yohanboniface** [comment]
Hi, thanks for this work, and sorry for my late answer.
Can you split this down in more atomic PRs?

**Comment by yohanboniface** [comment]
Or I can cherry pick while reviewing in you prefer/does not have time to dedicate to this.
Also minimal tests should be added ideally.

**Comment by yohanboniface** [comment]
Finally pushed a slightly simpler version for allowing rectangle drawing in any direction, including unit tests.
If you can come up with a simple separate PR for the Rectangle/Circle delayed commit, I'll review it quickly! :)
Closing here then.
Thanks again!

**Comment by xoqem** [comment]
@yohanboniface Thanks so much for going through these and making the nicer commits, I'll try them in my project this week!

**Pull request closed without merging**
