### PR TITLE
Allowing specifying layer class via options

### PR DESCRIPTION
**Pull request by hyperknot**

### CODE REVIEW

**Comment by yohanboniface** [comment]
Quick question: why not use `createLayer` directly instead in this case?

**Comment by hyperknot** [comment]
Do you mean overwriting `klass` from options? That's also an option, but I thought you want to keep option naming consistent with _this.options.

**Comment by yohanboniface** [comment]
No, I meant, instead of doing, for example:
```javascript
map.editTools.createRectangle({rectangleClass: MyClass}, …)
```
Why not doing:
```javascript
map.editTools.createLayer(MyClass, …)
```

**Comment by yohanboniface** [comment]
Humm, I think I know: because with your version you can pass the class as an option of startPolygon and co

**Comment by yohanboniface** [comment]
Thanks :)

**Comment by hyperknot** [comment]
Yes, of course, it is for startPolygon and etc., sorry for not explaining the use case before.

**Pull request merged**
