### PR TITLE
Add mouseover and mouseout events to VertexMarker

### PR DESCRIPTION
**Pull request by Git-Lior**
Hey,

This is just a simple change that exposes the `mouseover` and `mouseout` events of `VertexMarker`.
I need this to display a tooltip when the user's mouse enters the vertex marker and I'm sure it will be useful to others with different needs.

Thanks :smiley:

### CODE REVIEW

**Comment by yohanboniface** [comment]
Thanks, sounds good!
Would you mind adding basic unit tests?

**Comment by Git-Lior** [comment]
here you go :)

**Comment by pflans** [comment]
I believe this is because of the old version of node being used for the tests causing an error with [here](https://github.com/Medium/phantomjs/issues/753).

I believe changing package.json to "phantomjs-prebuilt": "2.1.15" would fix it. I can't get the tests to work locally at the moment to try it though.

**Comment by yohanboniface** [comment]
Merged from command line: https://github.com/Leaflet/Leaflet.Editable/commit/db8825d70a0f78e3209a1ba4ffe2e897729a265b

**Pull request closed without merging**
